version: "3.9"

services:
    zookeeper:
        restart: unless-stopped
        image: ubuntu/zookeeper:latest
        ports:
            - "2181:2181"

    kafka:
        image: ubuntu/kafka:latest
        entrypoint: /opt/kafka/bin/kafka-server-start.sh /etc/kafka/server.properties --override zookeeper.connect=zookeeper:2181 --override broker.id=1 --override advertised.listeners=PLAINTEXT://127.0.0.1:9092
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper

networks:
    samkafka:
